### ISSUE TITLE
Allow date placeholders in result sets

### ISSUE THREAD

**Issue by IanSchweer** [moertel/sQucumber-postgres#4]
Allow for the following `Then` clause:

```
Then the result exactly matches with date placeholders
| foo | date_bar  |
| 1     | 1 day ago |
```

**Comment by IanSchweer** [comment]
As a note, the work around for this is using `Then the result includes`

**Comment by moertel** [comment]
In order to keep support for adding explanatory text at the end, I changed the order for the `with date placeholders` keyphrase. You can now use this as follows:

 * Bare matcher:
```cucumber
Then the result exactly matches:
  | foo | date_bar   |
  | 1   | 2017-01-01 |
```
 * Matcher with placeholder:
```cucumber
Then the result exactly matches some expected state:
  | foo | date_bar   |
  | 1   | 2017-01-01 |
```
 * Matcher with placeholder and explanatory text:
```cucumber
Then the result with date placeholders exactly matches some expected state:
  | foo | date_bar  |
  | 1   | 1 day ago |
```
Placeholders have been added for all result matchers.
